version: '3.1'
services:
  mongo:
    image: ${MONGO_IMAGE}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - 27017:27017
